"use client"

import { useState } from "react"
import { cn } from "@/lib/utils"
import { GsCard, GsBadge, ProgressBar, PulseDot, AIChatWidget } from "@/components/greenstack-ui"
import { BIDS, fmt } from "@/lib/data"

const sections = ["overview", "technical", "pricing", "timeline", "team", "compliance"]
const statusC: Record<string, string> = { drafting: "yellow", review: "cyan", submitted: "purple", sourcing: "blue" }

export default function BidBuilderPage() {
  const [selected, setSelected] = useState(BIDS[0])
  const [section, setSection] = useState("overview")
  const [generating, setGenerating] = useState(false)
  const [content, setContent] = useState("")

  const generate = async () => {
    setGenerating(true)
    setContent("")
    await new Promise((r) => setTimeout(r, 2000))
    const demoContent = `## ${section.charAt(0).toUpperCase() + section.slice(1)} Section \u2014 ${selected.tender}

This ${section} has been generated by GreenStack AI based on analysis of successful UK sustainability tender submissions.

**Key Points:**
\u2022 Comprehensive methodology aligned with PAS 2035 and ISO 50001 standards
\u2022 Proven track record with ${Math.floor(Math.random() * 20 + 10)} similar projects delivered on time
\u2022 Competitive pricing structure with transparent cost breakdown
\u2022 Risk mitigation strategy covering supply chain, regulatory, and operational risks
\u2022 Dedicated project team with combined 40+ years sector experience

**Estimated Value:** ${fmt(selected.value)}
**Confidence Score:** ${selected.aiScore}/100
**Win Probability:** ${Math.floor(Math.random() * 20 + 60)}%

This section references relevant UK legislation including the Climate Change Act 2008, Energy Act 2023, and the UK Net Zero Strategy. All methodologies comply with TrustMark requirements and CIBSE guidelines.`
    setContent(demoContent)
    setGenerating(false)
  }

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-white">Bid Builder</h1>
        <p className="text-sm text-slate-500 mt-1">AI writes, optimises, and submits bids autonomously</p>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div className="space-y-3">
          <p className="text-xs font-mono text-slate-500 uppercase tracking-widest">Active Bids</p>
          {BIDS.map((b) => (
            <GsCard
              key={b.id}
              className={cn("p-4 cursor-pointer hover:border-white/10", selected?.id === b.id ? "border-emerald-500/25" : "")}
              glow={selected?.id === b.id}
              onClick={() => {
                setSelected(b)
                setContent("")
              }}
            >
              <div className="flex items-start justify-between mb-2">
                <p className="text-sm font-medium leading-snug text-white">{b.tender}</p>
                <GsBadge color={statusC[b.status]}>{b.status}</GsBadge>
              </div>
              <p className="text-xs font-mono text-slate-400 mb-3">{fmt(b.value)}</p>
              <ProgressBar value={b.progress} color={b.progress === 100 ? "#c084fc" : "#00ff87"} />
              <p className="text-xs text-slate-500 mt-1.5">
                {b.progress}% \u00B7 edited {b.lastEdit}
              </p>
            </GsCard>
          ))}
        </div>

        <div className="lg:col-span-2 space-y-4">
          <GsCard className="p-5">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h2 className="font-semibold text-white">{selected?.tender}</h2>
                <p className="text-xs text-slate-500 mt-0.5">
                  {fmt(selected?.value || 0)} \u00B7 AI Score: {selected?.aiScore}/100
                </p>
              </div>
              <div className="flex gap-2">
                <button className="px-4 py-2 rounded-xl bg-white/5 border border-white/10 text-sm text-slate-300 hover:bg-white/10 transition-all">
                  Save Draft
                </button>
                <button className="px-4 py-2 rounded-xl bg-emerald-500/20 border border-emerald-500/30 text-sm text-emerald-400 hover:bg-emerald-500/30 transition-all">
                  Submit Bid
                </button>
              </div>
            </div>
            <div className="flex gap-1.5 mb-4 flex-wrap">
              {sections.map((s) => (
                <button
                  key={s}
                  onClick={() => setSection(s)}
                  className={cn(
                    "px-3 py-1.5 rounded-lg text-xs font-medium capitalize transition-all",
                    section === s
                      ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30"
                      : "bg-white/5 text-slate-400 hover:bg-white/10 border border-transparent"
                  )}
                >
                  {s}
                </button>
              ))}
            </div>
            <button
              onClick={generate}
              disabled={generating}
              className="w-full py-3 rounded-xl border border-emerald-500/30 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 text-sm font-medium transition-all disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {generating ? (
                <>
                  <span className="animate-spin inline-block">{"\u27F3"}</span>AI Generating {section}...
                </>
              ) : (
                <>Generate {section} section</>
              )}
            </button>
          </GsCard>

          {(generating || content) && (
            <GsCard className="p-5">
              <div className="flex items-center justify-between mb-3">
                <p className="text-xs font-mono text-slate-500 uppercase tracking-widest">
                  {section} \u2014 AI Generated
                </p>
                {content && !generating && (
                  <button className="text-xs text-emerald-400 hover:text-emerald-300 transition-colors">
                    Accept {"\u2192"}
                  </button>
                )}
              </div>
              {generating ? (
                <div className="space-y-2">
                  {[90, 70, 85, 55, 75, 45].map((w, i) => (
                    <div
                      key={i}
                      className="h-3 rounded bg-white/5 animate-pulse"
                      style={{ width: `${w}%`, animationDelay: `${i * 100}ms` }}
                    />
                  ))}
                </div>
              ) : (
                <div className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap">{content}</div>
              )}
            </GsCard>
          )}

          <GsCard className="p-5" glow>
            <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-3 flex items-center gap-2">
              <PulseDot size={1.5} />
              Bid AI Assistant
            </p>
            <AIChatWidget
              placeholder="How can I improve this bid?"
              systemPrompt={`You are GreenStack's bid optimisation AI. You're improving a bid for: ${selected?.tender}, value ${fmt(selected?.value || 0)}.`}
            />
          </GsCard>
        </div>
      </div>
    </div>
  )
}
