'use client'

import { useState } from 'react'
import { cn } from '@/lib/utils'
import { GsCard, GsBadge, ProgressBar, PulseDot, AIChatWidget, StatCard } from '@/components/greenstack-ui'
import { BIDS, fmt } from '@/lib/data'
import { CheckCircle2, ChevronDown } from 'lucide-react'

const sections = ['overview', 'technical', 'pricing', 'timeline', 'team', 'compliance']
const statusC: Record<string, string> = { drafting: 'yellow', review: 'cyan', submitted: 'purple', sourcing: 'blue' }

export default function BidBuilderPage() {
  const [selected, setSelected] = useState(BIDS[0])
  const [section, setSection] = useState('overview')
  const [generating, setGenerating] = useState(false)
  const [content, setContent] = useState('')
  const [completedSections, setCompletedSections] = useState<string[]>([])

  const generate = async () => {
    setGenerating(true)
    setContent('')
    await new Promise((r) => setTimeout(r, 2000))
    const demoContent = `## ${section.charAt(0).toUpperCase() + section.slice(1)} Section — ${selected.tender}

This ${section} has been generated by GreenStack AI based on analysis of successful UK sustainability tender submissions.

**Key Points:**
• Comprehensive methodology aligned with PAS 2035 and ISO 50001 standards
• Proven track record with ${Math.floor(Math.random() * 20 + 10)} similar projects delivered on time
• Competitive pricing structure with transparent cost breakdown
• Risk mitigation strategy covering supply chain, regulatory, and operational risks
• Dedicated project team with combined 40+ years sector experience

**Estimated Value:** ${fmt(selected.value)}
**Confidence Score:** ${selected.aiScore}/100
**Win Probability:** ${Math.floor(Math.random() * 20 + 60)}%

This section references relevant UK legislation including the Climate Change Act 2008, Energy Act 2023, and the UK Net Zero Strategy. All methodologies comply with TrustMark requirements and CIBSE guidelines.`
    setContent(demoContent)
    if (!completedSections.includes(section)) {
      setCompletedSections([...completedSections, section])
    }
    setGenerating(false)
  }

  const progress = (completedSections.length / sections.length) * 100

  return (
    <div className="flex h-full bg-background">
      {/* Left - Section Checklist */}
      <div className="w-56 border-r border-white/5 overflow-y-auto p-5 flex flex-col gap-3">
        <div className="mb-2">
          <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-2">Progress</p>
          <div className="flex items-center gap-2 mb-2">
            <div className="flex-1 h-2 bg-white/5 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-emerald-500 to-cyan-400 transition-all duration-500"
                style={{ width: `${progress}%` }}
              />
            </div>
            <span className="text-xs text-emerald-400 font-mono">{Math.round(progress)}%</span>
          </div>
        </div>
        <div className="space-y-2">
          {sections.map((s) => {
            const isComplete = completedSections.includes(s)
            const isCurrent = section === s
            return (
              <button
                key={s}
                onClick={() => setSection(s)}
                className={cn(
                  'p-3 rounded-lg text-left text-sm transition-all flex items-center gap-2',
                  isCurrent
                    ? 'bg-emerald-500/10 border border-emerald-500/30 text-white'
                    : 'bg-white/5 border border-white/5 text-slate-400 hover:bg-white/10'
                )}
              >
                {isComplete && <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />}
                <span className="flex-1 capitalize">{s}</span>
              </button>
            )
          })}
        </div>
      </div>

      {/* Center - Content Editor */}
      <div className="flex-1 overflow-y-auto p-8">
        <div className="max-w-3xl">
          <div className="mb-6">
            <h2 className="text-2xl font-bold text-white mb-1 capitalize">{section} Section</h2>
            <p className="text-sm text-slate-500">
              {selected?.tender} · {fmt(selected?.value || 0)}
            </p>
          </div>

          <GsCard className="p-6 mb-6">
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="AI-generated content will appear here..."
              className="w-full h-80 bg-white/5 border border-white/10 rounded-lg px-4 py-3 text-sm text-white placeholder-slate-600 focus:outline-none focus:border-emerald-500/40 resize-none"
            />
          </GsCard>

          <div className="flex gap-3">
            <button
              onClick={generate}
              disabled={generating}
              className="px-4 py-2.5 bg-emerald-500/20 border border-emerald-500/30 rounded-lg text-emerald-400 text-sm font-medium hover:bg-emerald-500/30 transition-colors disabled:opacity-50 flex items-center gap-2"
            >
              {generating ? (
                <>
                  <span className="animate-spin inline-block">⟳</span>Generating...
                </>
              ) : (
                <>Generate with AI</>
              )}
            </button>
            <button className="px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-slate-300 text-sm font-medium hover:bg-white/10 transition-colors">
              Save Draft
            </button>
          </div>
        </div>
      </div>

      {/* Right - AI Suggestions */}
      <div className="w-80 border-l border-white/5 overflow-y-auto p-5 flex flex-col">
        <h3 className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-4">AI Assistant</h3>

        <GsCard className="p-4 bg-emerald-500/5 border-emerald-500/20 mb-4">
          <p className="text-xs text-slate-400 mb-3">
            {completedSections.length}/{sections.length} sections completed
          </p>
          <div className="space-y-1.5">
            {sections.map((s) => (
              <div key={s} className="flex items-center gap-2 text-xs">
                {completedSections.includes(s) ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <div className="w-3.5 h-3.5 rounded-full border border-slate-600" />
                )}
                <span className="capitalize text-slate-400">{s}</span>
              </div>
            ))}
          </div>
        </GsCard>

        <div className="flex-1 mb-4">
          <AIChatWidget
            placeholder="How can I improve this?"
            systemPrompt={`You are GreenStack's bid optimization AI. Current bid: ${selected?.tender}, Value: ${fmt(selected?.value || 0)}, Section: ${section}.`}
          />
        </div>

        <GsCard className="p-4 bg-white/5 border-white/10">
          <p className="text-xs text-slate-500 mb-3">Quick Actions</p>
          <button className="w-full px-3 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-xs text-slate-300 transition-colors">
            Save Draft
          </button>
          <button className="w-full px-3 py-2 bg-emerald-500/20 hover:bg-emerald-500/30 border border-emerald-500/30 rounded-lg text-xs text-emerald-400 transition-colors mt-2">
            Submit Bid
          </button>
        </GsCard>
      </div>
    </div>
  )
}
