'use client'

import { useState } from 'react'
import { cn } from '@/lib/utils'
import { GsCard, GsBadge, ProgressBar, PulseDot, AIChatWidget, StatCard } from '@/components/greenstack-ui'
import { BIDS, fmt } from '@/lib/data'
import { CheckCircle2 } from 'lucide-react'

const sections = ['overview', 'technical', 'pricing', 'timeline', 'team', 'compliance']
const statusC: Record<string, string> = { drafting: 'yellow', review: 'cyan', submitted: 'purple', sourcing: 'blue' }

export default function BidBuilderPage() {
  const [selectedBidId, setSelectedBidId] = useState<string | number | null>(null)
  
  const bids = BIDS
    id: b.id,
    tender: b.tender_title,
    value: b.value || 0,
    status: b.status || 'drafting',
    progress: b.progress || 0,
    aiScore: b.ai_score || 75,
    lastEdit: b.last_edit ? new Date(b.last_edit).toLocaleDateString() : 'Now',
    content: b.content || {},
  }))

  const [selected, setSelected] = useState(bids[0] || null)
  const [section, setSection] = useState('overview')
  const [generating, setGenerating] = useState(false)
  const [content, setContent] = useState('')
  const [completedSections, setCompletedSections] = useState<string[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [newBid, setNewBid] = useState({ tender_id: '', tender_title: '', value: '' })

  const handleAddBid = async () => {
    if (!newBid.tender_title.trim()) return
    try {
      await createBid({
        tender_id: newBid.tender_id || undefined,
        tender_title: newBid.tender_title,
        value: newBid.value ? parseInt(newBid.value) : undefined,
        status: 'drafting',
      })
      mutate()
      setShowAddModal(false)
      setNewBid({ tender_id: '', tender_title: '', value: '' })
    } catch (e) {
      console.error('Failed to create bid:', e)
    }
  }

  const generate = async () => {
    if (!selected) return
    setGenerating(true)
    setContent('')
    await new Promise((r) => setTimeout(r, 2000))
    const demoContent = `## ${section.charAt(0).toUpperCase() + section.slice(1)} Section — ${selected.tender}

This ${section} has been generated by GreenStack AI based on analysis of successful UK sustainability tender submissions.

**Key Points:**
• Comprehensive methodology aligned with PAS 2035 and ISO 50001 standards
• Proven track record with ${Math.floor(Math.random() * 20 + 10)} similar projects delivered on time
• Competitive pricing structure with transparent cost breakdown
• Risk mitigation strategy covering supply chain, regulatory, and operational risks
• Dedicated project team with combined 40+ years sector experience

**Estimated Value:** ${fmt(selected.value)}
**Confidence Score:** ${selected.aiScore}/100
**Win Probability:** ${Math.floor(Math.random() * 20 + 60)}%

This section references relevant UK legislation including the Climate Change Act 2008, Energy Act 2023, and the UK Net Zero Strategy. All methodologies comply with TrustMark requirements and CIBSE guidelines.`
    setContent(demoContent)
    if (!completedSections.includes(section)) {
      setCompletedSections([...completedSections, section])
    }
    setGenerating(false)
  }

  const progress = (completedSections.length / sections.length) * 100

  if (bids.length === 0 && !isDemo) {
    return (
      <div className="flex items-center justify-center h-full">
        <GsCard className="p-8 text-center max-w-md">
          <h2 className="text-xl font-bold text-white mb-2">No Bids Yet</h2>
          <p className="text-sm text-slate-500 mb-6">Create your first bid to start building AI-powered proposals.</p>
          <button
            onClick={() => setShowAddModal(true)}
            className="px-6 py-3 rounded-xl bg-emerald-500/20 border border-emerald-500/30 text-emerald-400 text-sm font-medium hover:bg-emerald-500/30 transition-all"
          >
            + Create First Bid
          </button>
          
          {showAddModal && (
            <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={() => setShowAddModal(false)}>
              <GsCard className="w-full max-w-lg p-6 text-left" onClick={e => e.stopPropagation()}>
                <h2 className="text-lg font-bold text-white mb-4">Create New Bid</h2>
                <div className="space-y-4">
                  <div>
                    <label className="text-xs text-slate-500 mb-1.5 block">Tender Title *</label>
                    <input
                      value={newBid.tender_title}
                      onChange={(e) => setNewBid({ ...newBid, tender_title: e.target.value })}
                      placeholder="e.g. NHS Trust Solar PV Installation"
                      className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500/40"
                    />
                  </div>
                  {tenders.length > 0 && (
                    <div>
                      <label className="text-xs text-slate-500 mb-1.5 block">Link to Tender (Optional)</label>
                      <select
                        value={newBid.tender_id}
                        onChange={(e) => {
                          const tender = tenders.find(t => t.id === e.target.value)
                          setNewBid({ 
                            ...newBid, 
                            tender_id: e.target.value,
                            tender_title: tender?.title || newBid.tender_title,
                            value: tender?.value?.toString() || newBid.value
                          })
                        }}
                        className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-emerald-500/40"
                      >
                        <option value="" className="bg-slate-900">None</option>
                        {tenders.map(t => (
                          <option key={t.id} value={t.id} className="bg-slate-900">{t.title}</option>
                        ))}
                      </select>
                    </div>
                  )}
                  <div>
                    <label className="text-xs text-slate-500 mb-1.5 block">Bid Value (GBP)</label>
                    <input
                      type="number"
                      value={newBid.value}
                      onChange={(e) => setNewBid({ ...newBid, value: e.target.value })}
                      placeholder="e.g. 500000"
                      className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500/40"
                    />
                  </div>
                </div>
                <div className="flex gap-3 mt-6">
                  <button
                    onClick={() => setShowAddModal(false)}
                    className="flex-1 py-2.5 rounded-xl bg-white/5 border border-white/10 text-slate-300 text-sm font-medium hover:bg-white/10 transition-all"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleAddBid}
                    disabled={!newBid.tender_title.trim()}
                    className="flex-1 py-2.5 rounded-xl bg-emerald-500/20 border border-emerald-500/30 text-emerald-400 text-sm font-medium hover:bg-emerald-500/30 transition-all disabled:opacity-50"
                  >
                    Create Bid
                  </button>
                </div>
              </GsCard>
            </div>
          )}
        </GsCard>
      </div>
    )
  }

  return (
    <div className="flex h-full bg-background">
      {/* Left - Bid List & Section Checklist */}
      <div className="w-64 border-r border-white/5 overflow-y-auto p-5 flex flex-col gap-4">
        <div>
          <div className="flex items-center justify-between mb-3">
            <p className="text-xs font-mono text-slate-500 uppercase tracking-widest">Your Bids</p>
            {!isDemo && (
              <button
                onClick={() => setShowAddModal(true)}
                className="text-xs text-emerald-400 hover:text-emerald-300"
              >
                + New
              </button>
            )}
          </div>
          <div className="space-y-2">
            {bids.map((b) => (
              <button
                key={b.id}
                onClick={() => {
                  setSelected(b)
                  setContent('')
                  setCompletedSections([])
                }}
                className={cn(
                  'w-full p-3 rounded-lg text-left text-sm transition-all',
                  selected?.id === b.id
                    ? 'bg-emerald-500/10 border border-emerald-500/30'
                    : 'bg-white/5 border border-white/5 hover:bg-white/10'
                )}
              >
                <p className="text-white text-sm font-medium truncate">{b.tender}</p>
                <p className="text-xs text-slate-500 mt-1">{fmt(b.value)}</p>
                <div className="flex items-center gap-2 mt-2">
                  <ProgressBar value={b.progress} color="#00ff87" />
                  <span className="text-xs text-slate-500">{b.progress}%</span>
                </div>
              </button>
            ))}
          </div>
        </div>

        <div className="border-t border-white/5 pt-4">
          <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-3">Sections</p>
          <div className="space-y-2">
            {sections.map((s) => {
              const isComplete = completedSections.includes(s)
              const isCurrent = section === s
              return (
                <button
                  key={s}
                  onClick={() => setSection(s)}
                  className={cn(
                    'w-full p-3 rounded-lg text-left text-sm transition-all flex items-center gap-2',
                    isCurrent
                      ? 'bg-emerald-500/10 border border-emerald-500/30 text-white'
                      : 'bg-white/5 border border-white/5 text-slate-400 hover:bg-white/10'
                  )}
                >
                  {isComplete && <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />}
                  <span className="flex-1 capitalize">{s}</span>
                </button>
              )
            })}
          </div>
        </div>
      </div>

      {/* Center - Content Editor */}
      <div className="flex-1 overflow-y-auto p-8">
        <div className="max-w-3xl">
          <div className="mb-6">
            <h2 className="text-2xl font-bold text-white mb-1 capitalize">{section} Section</h2>
            <p className="text-sm text-slate-500">
              {selected?.tender} · {fmt(selected?.value || 0)}
            </p>
          </div>

          <GsCard className="p-6 mb-6">
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="AI-generated content will appear here. Click 'Generate with AI' to start..."
              className="w-full h-80 bg-white/5 border border-white/10 rounded-lg px-4 py-3 text-sm text-white placeholder-slate-600 focus:outline-none focus:border-emerald-500/40 resize-none"
            />
          </GsCard>

          <div className="flex gap-3">
            <button
              onClick={generate}
              disabled={generating}
              className="px-4 py-2.5 bg-emerald-500/20 border border-emerald-500/30 rounded-lg text-emerald-400 text-sm font-medium hover:bg-emerald-500/30 transition-colors disabled:opacity-50 flex items-center gap-2"
            >
              {generating ? (
                <>
                  <span className="animate-spin inline-block">{"\u27F3"}</span>Generating...
                </>
              ) : (
                <>Generate with AI</>
              )}
            </button>
            <button className="px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-slate-300 text-sm font-medium hover:bg-white/10 transition-colors">
              Save Draft
            </button>
          </div>
        </div>
      </div>

      {/* Right - AI Assistant */}
      <div className="w-80 border-l border-white/5 overflow-y-auto p-5 flex flex-col">
        <h3 className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-4">AI Assistant</h3>

        <GsCard className="p-4 bg-emerald-500/5 border-emerald-500/20 mb-4">
          <p className="text-xs text-slate-400 mb-3">
            {completedSections.length}/{sections.length} sections completed
          </p>
          <div className="space-y-1.5">
            {sections.map((s) => (
              <div key={s} className="flex items-center gap-2 text-xs">
                {completedSections.includes(s) ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <div className="w-3.5 h-3.5 rounded-full border border-slate-600" />
                )}
                <span className="capitalize text-slate-400">{s}</span>
              </div>
            ))}
          </div>
        </GsCard>

        <div className="flex-1 mb-4">
          <AIChatWidget
            placeholder="How can I improve this?"
            systemPrompt={`You are GreenStack's bid optimization AI. Current bid: ${selected?.tender}, Value: ${fmt(selected?.value || 0)}, Section: ${section}.`}
          />
        </div>

        <GsCard className="p-4 bg-white/5 border-white/10">
          <p className="text-xs text-slate-500 mb-3">Quick Actions</p>
          <button className="w-full px-3 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-xs text-slate-300 transition-colors">
            Save Draft
          </button>
          <button className="w-full px-3 py-2 bg-emerald-500/20 hover:bg-emerald-500/30 border border-emerald-500/30 rounded-lg text-xs text-emerald-400 transition-colors mt-2">
            Submit Bid
          </button>
        </GsCard>
      </div>

      {/* Add Bid Modal */}
      {showAddModal && (
        <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={() => setShowAddModal(false)}>
          <GsCard className="w-full max-w-lg p-6" onClick={e => e.stopPropagation()}>
            <h2 className="text-lg font-bold text-white mb-4">Create New Bid</h2>
            <div className="space-y-4">
              <div>
                <label className="text-xs text-slate-500 mb-1.5 block">Tender Title *</label>
                <input
                  value={newBid.tender_title}
                  onChange={(e) => setNewBid({ ...newBid, tender_title: e.target.value })}
                  placeholder="e.g. NHS Trust Solar PV Installation"
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500/40"
                />
              </div>
              {tenders.length > 0 && (
                <div>
                  <label className="text-xs text-slate-500 mb-1.5 block">Link to Tender (Optional)</label>
                  <select
                    value={newBid.tender_id}
                    onChange={(e) => {
                      const tender = tenders.find(t => t.id === e.target.value)
                      setNewBid({ 
                        ...newBid, 
                        tender_id: e.target.value,
                        tender_title: tender?.title || newBid.tender_title,
                        value: tender?.value?.toString() || newBid.value
                      })
                    }}
                    className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-emerald-500/40"
                  >
                    <option value="" className="bg-slate-900">None</option>
                    {tenders.map(t => (
                      <option key={t.id} value={t.id} className="bg-slate-900">{t.title}</option>
                    ))}
                  </select>
                </div>
              )}
              <div>
                <label className="text-xs text-slate-500 mb-1.5 block">Bid Value (GBP)</label>
                <input
                  type="number"
                  value={newBid.value}
                  onChange={(e) => setNewBid({ ...newBid, value: e.target.value })}
                  placeholder="e.g. 500000"
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500/40"
                />
              </div>
            </div>
            <div className="flex gap-3 mt-6">
              <button
                onClick={() => setShowAddModal(false)}
                className="flex-1 py-2.5 rounded-xl bg-white/5 border border-white/10 text-slate-300 text-sm font-medium hover:bg-white/10 transition-all"
              >
                Cancel
              </button>
              <button
                onClick={handleAddBid}
                disabled={!newBid.tender_title.trim()}
                className="flex-1 py-2.5 rounded-xl bg-emerald-500/20 border border-emerald-500/30 text-emerald-400 text-sm font-medium hover:bg-emerald-500/30 transition-all disabled:opacity-50"
              >
                Create Bid
              </button>
            </div>
          </GsCard>
        </div>
      )}
    </div>
  )
}
