'use client'

import { useState, useEffect } from 'react'
import { GsCard, PulseDot, AIChatWidget, StatCard } from '@/components/greenstack-ui'
import { REPORTS } from '@/lib/data'
import { LineChart, Line, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'

const reportTypes = [
  'Q1 2026 Performance Report',
  'AI Bid Optimisation Analysis',
  'Supply Chain Health Check',
  'Carbon Impact Summary',
  'Win Rate Deep Dive',
  'Revenue Forecast Q2 2026',
]

const kpis = [
  { l: 'Total Bids', v: '183', c: '#00ff87' },
  { l: 'Won', v: '62', c: '#60efff' },
  { l: 'Win Rate', v: '34%', c: '#ffd166' },
  { l: 'Revenue', v: '£420K', c: '#c084fc' },
  { l: 'Pipeline', v: '£2.4M', c: '#00ff87' },
  { l: 'Avg Bid', v: '£38K', c: '#60efff' },
]

const timeSeriesData = [
  { month: 'Jan', bids: 45, won: 14, revenue: 95 },
  { month: 'Feb', bids: 58, won: 18, revenue: 142 },
  { month: 'Mar', bids: 80, won: 30, revenue: 183 },
]

const sectorData = [
  { name: 'Aviation', value: 45, fill: '#00ff87' },
  { name: 'Local Authority', value: 30, fill: '#60efff' },
  { name: 'Healthcare', value: 15, fill: '#a78bfa' },
  { name: 'Utilities', value: 10, fill: '#ffd166' },
]

const bidPerformanceData = [
  { name: 'AI Bids', 'Win Rate': 41 },
  { name: 'Manual Bids', 'Win Rate': 24 },
]

export default function ReportsPage() {
  const [reportType, setReportType] = useState('Q1 2026 Performance Report')
  const [period, setPeriod] = useState('Q1 2026')
  const [generating, setGenerating] = useState(false)
  const [report, setReport] = useState('')
  const [mounted, setMounted] = useState(false)
  
  useEffect(() => {
    setTimeout(() => setMounted(true), 80)
  }, [])

  const generate = async () => {
    setGenerating(true)
    setReport('')
    await new Promise((r) => setTimeout(r, 2200))
    setReport(`## ${reportType}

### Executive Summary
GreenStack platform performance continues to exceed targets across all key metrics in Q1 2026. AI-driven bid optimisation has improved win rates by 4 percentage points to 34%, while the pipeline has grown to £2.4M.

### Key Metrics
• **Total Bids Submitted:** 183 (+23% QoQ)
• **Bids Won:** 62 (34% win rate, up from 30%)
• **Revenue Generated:** £420K (+18% QoQ)
• **Active Pipeline:** £2.4M across 47 live tenders
• **Contractor Network:** 6 vetted suppliers, 4 preferred

### AI Performance Analysis
• AI-drafted bids have a 41% win rate vs 24% for manual bids
• Average bid completion time reduced from 12 days to 3.5 days
• AI tender matching accuracy: 87% (up from 79%)
• Cost per bid reduced by 62% through automation

### Sector Breakdown
• Aviation: £2.1M pipeline, 2 active bids
• Local Authority: £1.8M pipeline, 3 active bids
• Healthcare: £1.2M pipeline, 1 active bid
• Utilities: £1.5M pipeline, 1 active bid

### Strategic Recommendations
1. **Expand into Transport sector** — Growing opportunity with £890K Liverpool Port contract
2. **Increase AI bid automation** — Target 80% of bids AI-generated by Q2
3. **Contractor network growth** — Add 4 new preferred suppliers in Heat Pump and BEMS
4. **Win rate target** — Aim for 38% by end of Q2 through improved pricing models`)
    setGenerating(false)
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white">Reports & Analytics</h1>
          <p className="text-sm text-slate-500 mt-1">Multi-chart dashboard with AI insights and forecasting</p>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-3 sm:grid-cols-6 gap-3">
        {kpis.map((k, i) => (
          <GsCard key={i} className="p-4 text-center hover:border-white/10 transition-all">
            <p className="text-xs text-slate-500 mb-2">{k.l}</p>
            <p className="text-xl font-bold font-mono" style={{ color: k.c }}>
              {k.v}
            </p>
          </GsCard>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Main Dashboard Area */}
        <div className="lg:col-span-2 space-y-4">
          {/* Report Generation */}
          <GsCard className="p-5" glow>
            <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-4">Generate AI Report</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
              <div>
                <label className="text-xs text-slate-500 mb-1.5 block">Report Type</label>
                <select
                  value={reportType}
                  onChange={(e) => setReportType(e.target.value)}
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-emerald-500/40"
                >
                  {reportTypes.map((t) => (
                    <option key={t} value={t} className="bg-slate-900 text-white">
                      {t}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="text-xs text-slate-500 mb-1.5 block">Period</label>
                <select value={period} onChange={(e) => setPeriod(e.target.value)} className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-emerald-500/40">
                  {['Q1 2026', 'Q4 2025', 'Last 30 days', 'Last 90 days', 'YTD'].map((p) => (
                    <option key={p} className="bg-slate-900 text-white">
                      {p}
                    </option>
                  ))}
                </select>
              </div>
            </div>
            <button
              onClick={generate}
              disabled={generating}
              className="w-full py-3 rounded-xl border border-emerald-500/30 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 text-sm font-medium transition-all disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {generating ? (
                <>
                  <span className="animate-spin inline-block">⟳</span>AI Generating...
                </>
              ) : (
                <>Generate Report</>
              )}
            </button>
          </GsCard>

          {/* Charts Grid */}
          {mounted && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Line Chart - Bids Over Time */}
            <GsCard className="p-5">
              <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-4">Bid Submissions (Q1 2026)</p>
              <ResponsiveContainer width="100%" height={200}>
                <LineChart data={timeSeriesData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
                  <XAxis dataKey="month" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                  <YAxis tick={{ fill: '#64748b', fontSize: 11 }} />
                  <Tooltip contentStyle={{ background: 'rgba(2,10,20,0.95)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px' }} />
                  <Line type="monotone" dataKey="bids" stroke="#00ff87" strokeWidth={2} dot={{ fill: '#00ff87', r: 3 }} />
                </LineChart>
              </ResponsiveContainer>
            </GsCard>

            {/* Bar Chart - AI vs Manual Performance */}
            <GsCard className="p-5">
              <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-4">AI vs Manual Win Rate</p>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={bidPerformanceData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
                  <XAxis dataKey="name" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                  <YAxis tick={{ fill: '#64748b', fontSize: 11 }} />
                  <Tooltip contentStyle={{ background: 'rgba(2,10,20,0.95)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px' }} />
                  <Bar dataKey="Win Rate" fill="#00ff87" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </GsCard>

            {/* Pie Chart - Sector Breakdown */}
            <GsCard className="p-5">
              <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-4">Pipeline by Sector</p>
              <ResponsiveContainer width="100%" height={200}>
                <PieChart>
                  <Pie
                    data={sectorData}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    dataKey="value"
                    label={({ name, value }) => `${name} £${value}K`}
                  >
                    {sectorData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.fill} />
                    ))}
                  </Pie>
                </PieChart>
              </ResponsiveContainer>
            </GsCard>

            {/* Revenue Chart */}
            <GsCard className="p-5">
              <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-4">Revenue Trend</p>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={timeSeriesData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
                  <XAxis dataKey="month" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                  <YAxis tick={{ fill: '#64748b', fontSize: 11 }} />
                  <Tooltip contentStyle={{ background: 'rgba(2,10,20,0.95)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px' }} />
                  <Bar dataKey="revenue" fill="#60efff" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </GsCard>
          </div>
          )}

          {/* Generated Report */}
          {(generating || report) && (
            <GsCard className="p-5">
              <div className="flex items-center justify-between mb-4">
                <p className="text-xs font-mono text-slate-500 uppercase tracking-widest">{reportType}</p>
                {report && !generating && (
                  <div className="flex gap-2">
                    <button className="text-xs px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10 transition-all">
                      Export PDF
                    </button>
                    <button className="text-xs px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10 transition-all">
                      Share
                    </button>
                  </div>
                )}
              </div>
              {generating ? (
                <div className="space-y-2">
                  {[90, 70, 85, 60, 95, 45, 75, 55, 80, 65].map((w, i) => (
                    <div
                      key={i}
                      className="h-3 rounded bg-white/5 animate-pulse"
                      style={{ width: `${w}%`, animationDelay: `${i * 80}ms` }}
                    />
                  ))}
                </div>
              ) : (
                <div className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap">{report}</div>
              )}
            </GsCard>
          )}
        </div>

        {/* Right - Recent Reports + AI Chat */}
        <div className="space-y-3">
          <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-3">Recent Reports</p>
          <div className="space-y-2 mb-4">
            {REPORTS.map((r) => (
              <GsCard key={r.id} className="p-4 hover:border-white/10 transition-all cursor-pointer">
                <p className="text-sm font-medium mb-1 text-white">{r.title}</p>
                <p className="text-xs text-slate-500 mb-2">
                  {r.type} · {r.date}
                </p>
                {r.winRate && (
                  <div className="flex gap-3">
                    <div>
                      <p className="text-xs text-slate-600">Win Rate</p>
                      <p className="text-sm font-mono text-emerald-400">{r.winRate}</p>
                    </div>
                    <div>
                      <p className="text-xs text-slate-600">Value</p>
                      <p className="text-sm font-mono text-cyan-400">{r.value}</p>
                    </div>
                  </div>
                )}
              </GsCard>
            ))}
          </div>

          <GsCard className="p-4" glow>
            <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-3 flex items-center gap-2">
              <PulseDot size={1.5} />
              Ask AI About Data
            </p>
            <AIChatWidget
              placeholder="e.g. Why is win rate 34%?"
              systemPrompt="You are GreenStack's analytics AI. Stats: 183 bids, 34% win rate, £2.4M pipeline, 47 tenders, 6 contractors."
            />
          </GsCard>
        </div>
      </div>
    </div>
  )
}
