"use client"

import { useState } from "react"
import { GsCard, PulseDot, AIChatWidget } from "@/components/greenstack-ui"
import { REPORTS } from "@/lib/data"

const reportTypes = [
  "Q1 2026 Performance Report",
  "AI Bid Optimisation Analysis",
  "Supply Chain Health Check",
  "Carbon Impact Summary",
  "Win Rate Deep Dive",
  "Revenue Forecast Q2 2026",
]

const kpis = [
  { l: "Total Bids", v: "183", c: "#00ff87" },
  { l: "Won", v: "62", c: "#60efff" },
  { l: "Win Rate", v: "34%", c: "#ffd166" },
  { l: "Revenue", v: "\u00A3420K", c: "#c084fc" },
  { l: "Pipeline", v: "\u00A32.4M", c: "#00ff87" },
  { l: "Avg Bid", v: "\u00A338K", c: "#60efff" },
]

export default function ReportsPage() {
  const [reportType, setReportType] = useState("Q1 2026 Performance Report")
  const [generating, setGenerating] = useState(false)
  const [report, setReport] = useState("")

  const generate = async () => {
    setGenerating(true)
    setReport("")
    await new Promise((r) => setTimeout(r, 2200))
    setReport(`## ${reportType}

### Executive Summary
GreenStack platform performance continues to exceed targets across all key metrics in Q1 2026. AI-driven bid optimisation has improved win rates by 4 percentage points to 34%, while the pipeline has grown to \u00A32.4M.

### Key Metrics
\u2022 **Total Bids Submitted:** 183 (+23% QoQ)
\u2022 **Bids Won:** 62 (34% win rate, up from 30%)
\u2022 **Revenue Generated:** \u00A3420K (+18% QoQ)
\u2022 **Active Pipeline:** \u00A32.4M across 47 live tenders
\u2022 **Contractor Network:** 6 vetted suppliers, 4 preferred

### AI Performance Analysis
\u2022 AI-drafted bids have a 41% win rate vs 24% for manual bids
\u2022 Average bid completion time reduced from 12 days to 3.5 days
\u2022 AI tender matching accuracy: 87% (up from 79%)
\u2022 Cost per bid reduced by 62% through automation

### Sector Breakdown
\u2022 Aviation: \u00A32.1M pipeline, 2 active bids
\u2022 Local Authority: \u00A31.8M pipeline, 3 active bids
\u2022 Healthcare: \u00A31.2M pipeline, 1 active bid
\u2022 Utilities: \u00A31.5M pipeline, 1 active bid

### Strategic Recommendations
1. **Expand into Transport sector** \u2014 Growing opportunity with \u00A3890K Liverpool Port contract
2. **Increase AI bid automation** \u2014 Target 80% of bids AI-generated by Q2
3. **Contractor network growth** \u2014 Add 4 new preferred suppliers in Heat Pump and BEMS
4. **Win rate target** \u2014 Aim for 38% by end of Q2 through improved pricing models`)
    setGenerating(false)
  }

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-white">Reports & Analytics</h1>
        <p className="text-sm text-slate-500 mt-1">AI-generated insights across your entire platform</p>
      </div>
      <div className="grid grid-cols-3 sm:grid-cols-6 gap-3">
        {kpis.map((k, i) => (
          <GsCard key={i} className="p-4 text-center">
            <p className="text-xs text-slate-500 mb-2">{k.l}</p>
            <p className="text-xl font-bold font-mono" style={{ color: k.c }}>
              {k.v}
            </p>
          </GsCard>
        ))}
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div className="lg:col-span-2 space-y-4">
          <GsCard className="p-5" glow>
            <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-4">Generate AI Report</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
              <div>
                <label className="text-xs text-slate-500 mb-1.5 block">Report Type</label>
                <select
                  value={reportType}
                  onChange={(e) => setReportType(e.target.value)}
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-emerald-500/40"
                >
                  {reportTypes.map((t) => (
                    <option key={t} value={t} className="bg-slate-900 text-white">
                      {t}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="text-xs text-slate-500 mb-1.5 block">Period</label>
                <select className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-emerald-500/40">
                  {["Q1 2026", "Q4 2025", "Last 30 days", "Last 90 days", "YTD"].map((p) => (
                    <option key={p} className="bg-slate-900 text-white">
                      {p}
                    </option>
                  ))}
                </select>
              </div>
            </div>
            <button
              onClick={generate}
              disabled={generating}
              className="w-full py-3 rounded-xl border border-emerald-500/30 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 text-sm font-medium transition-all disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {generating ? (
                <>
                  <span className="animate-spin inline-block">{"\u27F3"}</span>AI Generating...
                </>
              ) : (
                <>Generate Report</>
              )}
            </button>
          </GsCard>
          {(generating || report) && (
            <GsCard className="p-5">
              <div className="flex items-center justify-between mb-4">
                <p className="text-xs font-mono text-slate-500 uppercase tracking-widest">{reportType}</p>
                {report && !generating && (
                  <div className="flex gap-2">
                    <button className="text-xs px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10 transition-all">
                      Export PDF
                    </button>
                    <button className="text-xs px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10 transition-all">
                      Share
                    </button>
                  </div>
                )}
              </div>
              {generating ? (
                <div className="space-y-2">
                  {[90, 70, 85, 60, 95, 45, 75, 55, 80, 65].map((w, i) => (
                    <div key={i} className="h-3 rounded bg-white/5 animate-pulse" style={{ width: `${w}%`, animationDelay: `${i * 80}ms` }} />
                  ))}
                </div>
              ) : (
                <div className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap">{report}</div>
              )}
            </GsCard>
          )}
        </div>
        <div className="space-y-3">
          <p className="text-xs font-mono text-slate-500 uppercase tracking-widest">Recent Reports</p>
          {REPORTS.map((r) => (
            <GsCard key={r.id} className="p-4 hover:border-white/10 transition-all cursor-pointer">
              <p className="text-sm font-medium mb-1 text-white">{r.title}</p>
              <p className="text-xs text-slate-500">
                {r.type} \u00B7 {r.date}
              </p>
              {r.winRate && (
                <div className="mt-2 pt-2 border-t border-white/5 flex gap-3">
                  <div>
                    <p className="text-xs text-slate-500">Win Rate</p>
                    <p className="text-sm font-mono text-emerald-400">{r.winRate}</p>
                  </div>
                  <div>
                    <p className="text-xs text-slate-500">Value</p>
                    <p className="text-sm font-mono text-cyan-400">{r.value}</p>
                  </div>
                </div>
              )}
            </GsCard>
          ))}
          <GsCard className="p-4 mt-2" glow>
            <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-3 flex items-center gap-2">
              <PulseDot size={1.5} />
              Ask AI About Data
            </p>
            <AIChatWidget
              placeholder="e.g. Why is win rate 34%?"
              systemPrompt="You are GreenStack's analytics AI. Stats: 183 bids, 34% win rate, \u00A32.4M pipeline, 47 tenders, 6 contractors."
            />
          </GsCard>
        </div>
      </div>
    </div>
  )
}
